workflows:
  expo-android:
    # Builds a debug APK on pull requests for testing purposes.
    name: NewPitara – Android APK (Debug)
    max_build_duration: 90
    instance_type: mac_mini_m2
    
    environment:
      node: "18.18.0"
      java: "17"
      vars:
        PROJECT_DIR: "apps/mobile"
        NODE_OPTIONS: "--max_old_space_size=4096"
        NODE_ENV: "development"
        EXPO_NO_DOTENV: "1"
        
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*" # Build on any branch PR
          include: true
      # a new build.
      cancel_previous_builds: true
          
    scripts:
      - name: Change to project directory
        script: |
          cd "$PROJECT_DIR"
          echo "📁 Working directory: $(pwd)"

      - name: Install npm dependencies
        script: |
          cd "$PROJECT_DIR"
          npm cache clean --force
          npm ci --legacy-peer-deps --no-audit --no-fund
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@^0.16.1
          npx expo --version
          echo "✅ Expo CLI installed successfully"

      - name: Expo prebuild (Android)
        script: |
          cd "$PROJECT_DIR"
          rm -rf android
          npx expo prebuild --platform android --clean --no-install
          
      - name: Build Android Debug APK
        script: |
          cd "$PROJECT_DIR"/android
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace
          
    artifacts:
      - "$PROJECT_DIR/android/app/build/outputs/apk/debug/*.apk"

  expo-android-release:
    # Builds a signed, production-ready release APK using EAS Build
    name: NewPitara – Android Release APK (EAS Build)
    max_build_duration: 90
    instance_type: mac_mini_m2
    
          environment:
        node: "18.18.0"
        vars:
          PROJECT_DIR: "apps/mobile"
          NODE_OPTIONS: "--max_old_space_size=4096"
          NODE_ENV: "production"
          EXPO_NO_DOTENV: "1"
        groups:
          - x # IMPORTANT: Ensure this group contains all required secrets including EXPO_TOKEN
        
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
      # a new build.
      cancel_previous_builds: true
          
    scripts:
      - name: Change to project directory
        script: |
          cd "$PROJECT_DIR"
          echo "📁 Working directory: $(pwd)"

      - name: Install npm dependencies
        script: |
          echo "📁 Installing dependencies from monorepo root: $(pwd)"
          npm cache clean --force
          npm ci --legacy-peer-deps --no-audit --no-fund
          
      - name: Install EAS CLI
        script: |
          npm install -g @expo/cli@^0.16.1 eas-cli@latest
          npx expo --version
          eas --version
          echo "✅ EAS CLI installed successfully"

      - name: Set up environment variables
        script: |
          cd "$PROJECT_DIR"
          cat > .env << EOF
          EXPO_PUBLIC_SUPABASE_URL=$EXPO_PUBLIC_SUPABASE_URL
          EXPO_PUBLIC_SUPABASE_ANON_KEY=$EXPO_PUBLIC_SUPABASE_ANON_KEY
          SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
          SUPABASE_ACCESS_TOKEN=$SUPABASE_ACCESS_TOKEN
          SUPABASE_PROJECT_REF=$SUPABASE_PROJECT_REF
          SUPABASE_DB_URL=$SUPABASE_DB_URL
          EXPO_PUBLIC_RAZORPAY_KEY=$EXPO_PUBLIC_RAZORPAY_KEY
          EXPO_PUBLIC_RAZORPAY_KEY_SECRET=$EXPO_PUBLIC_RAZORPAY_KEY_SECRET
          EXPO_PUBLIC_RAZORPAY_WEBHOOK_SECRET=$EXPO_PUBLIC_RAZORPAY_WEBHOOK_SECRET
          EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
          EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID
          EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID
          EXPO_PUBLIC_GOOGLE_WEB_CLIENT_SECRET=$EXPO_PUBLIC_GOOGLE_WEB_CLIENT_SECRET
          EXPO_PUBLIC_BYPASS_AUTH=$EXPO_PUBLIC_BYPASS_AUTH
          EXPO_PUBLIC_BUNNY_CDN_URL=$EXPO_PUBLIC_BUNNY_CDN_URL
          EOF
          echo "✅ Environment variables configured"

      - name: Configure EAS credentials
        script: |
          cd "$PROJECT_DIR"
          echo "🔐 Setting up EAS credentials..."
          
          # Create EAS credentials file
          mkdir -p ~/.expo
          cat > ~/.expo/auth.json << EOF
          {
            "sessionSecret": "$EXPO_TOKEN"
          }
          EOF
          
          echo "✅ EAS credentials configured"

      - name: Build Android APK with EAS
        script: |
          cd "$PROJECT_DIR"
          
          echo "🔨 Building Android APK using EAS..."
          
          # Build APK using EAS
          eas build --platform android --profile production --non-interactive --local --output build.apk
          
          echo "📦 Checking for APK files..."
          ls -la *.apk || echo "No APK files found in current directory"
          
          if [ -f "build.apk" ]; then
            echo "✅ APK built successfully!"
            ls -la build.apk
          else
            echo "❌ APK not found!"
            echo "📁 Checking for any APK files:"
            find . -name "*.apk" -type f || echo "No APK files found anywhere"
            exit 1
          fi

      - name: Copy APK to artifacts directory
        script: |
          echo "📁 Creating artifacts directory..."
          mkdir -p $CM_BUILD_DIR/artifacts
          
          cd "$PROJECT_DIR"
          echo "🔍 Looking for APK files..."
          find . -name "*.apk" -type f
          
          if [ -f "build.apk" ]; then
            echo "✅ Copying main APK..."
            cp "build.apk" "$CM_BUILD_DIR/artifacts/pitara-release.apk"
          fi
          
          # Copy any other APK files found
          find . -name "*.apk" -exec cp {} $CM_BUILD_DIR/artifacts/ \; 2>/dev/null || echo "No additional APK files found"
          
          echo "📦 Final artifacts:"
          ls -la $CM_BUILD_DIR/artifacts/ || echo "No artifacts directory found"

    artifacts:
      - $PROJECT_DIR/android/app/build/outputs/apk/release/*.apk
      - $CM_BUILD_DIR/artifacts/*.apk
      
    publishing:
      email:
        recipients:
          - pitarasupabase@gmail.com
        notify:
          success: true
          failure: true 