workflows:
  android-apk:
    name: "React Native • Android APK"
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      # Tools
      node: 20.10.0          # Match your local Node version
      java: 17               # Required for modern Android Gradle plugin
      
      # Environment variables that will be provided securely in Codemagic UI
      groups:
        - android_keystore   # CM_KEYSTORE, CM_KEYSTORE_FILENAME, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS

      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        PROJECT_DIR: "apps/mobile"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Change to project directory
        script: |
          cd "$PROJECT_DIR"

      - name: Install dependencies
        script: |
          cd "$PROJECT_DIR"
          npm ci

      - name: Decode Android keystore (optional)
        script: |
          cd "$PROJECT_DIR"
          # Only runs if keystore variables are set in the android_keystore group
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 --decode > android/app/$CM_KEYSTORE_FILENAME
          fi

      - name: Build release APK
        script: |
          cd "$PROJECT_DIR"/android
          ./gradlew assembleRelease --no-daemon --stacktrace

    artifacts:
      # Path is relative to the repository root
      - apps/mobile/android/app/build/outputs/**/*.apk

  expo-android:
    # Builds the Expo Router app under newpitara/apps/mobile and outputs an unsigned APK
    name: NewPitara – Android APK (Expo)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      node: "18.18.0"     # Expo SDK 52 supports Node 18
      java: "17"          # Required by modern Android Gradle Plugin
      
      vars:
        PROJECT_DIR: "apps/mobile"
        
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          
    scripts:
      # 1. Install JS dependencies
      - name: Install npm dependencies
        script: |
          cd "$PROJECT_DIR"
          npm ci --legacy-peer-deps

      # 2. Generate the native Android project (creates android/ folder)
      - name: Expo prebuild (Android)
        script: |
          cd "$PROJECT_DIR"
          npx expo prebuild --platform android --non-interactive --no-install

      # 3. Compile a release APK (unsigned). Switch to assembleDebug for debug builds
      - name: Compile Android APK
        script: |
          cd "$PROJECT_DIR"/android
          ./gradlew assembleRelease --warning-mode all --no-daemon

    artifacts:
      # Collect APK(s) produced during the build
      - "$PROJECT_DIR/android/app/build/outputs/**/*.apk"

    # Remove email publishing to avoid validation errors
    # You can configure email notifications in Codemagic UI instead 