workflows:
  expo-android:
    # Builds the Expo Router app under newpitara/apps/mobile and outputs an unsigned APK
    name: NewPitara – Android APK (Expo)
    max_build_duration: 90
    instance_type: mac_mini_m2
    
    environment:
      node: "18.18.0"     # Expo SDK 52 supports Node 18
      java: "17"          # Required by modern Android Gradle Plugin
      
      # Environment variables that will be provided securely in Codemagic UI
      groups:
        - android_keystore   # CM_KEYSTORE, CM_KEYSTORE_FILENAME, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS
      
      vars:
        PROJECT_DIR: "apps/mobile"
        NODE_OPTIONS: "--max_old_space_size=4096"
        NODE_ENV: "production"
        EXPO_NO_DOTENV: "1"
        
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
      cancel_previous_builds: true
          
    scripts:
      # 1. Change to project directory
      - name: Change to project directory
        script: |
          cd "$PROJECT_DIR"
          pwd
          ls -la

      # 2. Clean npm cache and install dependencies
      - name: Install npm dependencies
        script: |
          cd "$PROJECT_DIR"
          # Clean npm cache and start fresh
          npm cache clean --force
          rm -rf package-lock.json node_modules
          # Install dependencies with proper flags
          npm install --legacy-peer-deps --force
          
      # 3. Install Expo CLI globally with specific version
      - name: Install Expo CLI
        script: |
          # Install specific Expo CLI version compatible with SDK 52
          npm install -g @expo/cli@latest
          # Verify installation
          npx expo --version
          echo "Expo CLI installed successfully"

      # 4. Generate the native Android project (creates android/ folder)
      - name: Expo prebuild (Android)
        script: |
          cd "$PROJECT_DIR"
          # Set environment variables for prebuild
          export NODE_ENV=production
          export EXPO_NO_DOTENV=1
          # Clear any existing android directory
          rm -rf android
          # Generate native Android project with verbose output
          npx expo prebuild --platform android --clean --non-interactive --no-install
          
      # 5. Verify Android project was created
      - name: Verify Android project
        script: |
          cd "$PROJECT_DIR"
          if [ ! -d "android" ]; then
            echo "❌ Android directory not created by expo prebuild"
            exit 1
          fi
          if [ ! -f "android/gradlew" ]; then
            echo "❌ gradlew not found in android directory"
            exit 1
          fi
          echo "✅ Android project structure verified"
          ls -la android/

      # 6. Pre-bundle JavaScript (to catch bundling errors early)
      - name: Pre-bundle JavaScript
        script: |
          cd "$PROJECT_DIR"  
          # Set environment variables for bundling
          export NODE_ENV=production
          export EXPO_NO_DOTENV=1
          # Try to bundle JavaScript without building APK to catch errors early
          npx expo export --platform android --clear || echo "Pre-bundling failed, will try alternative approach"

      # 7. Decode Android keystore (optional)
      - name: Decode Android keystore (optional)
        script: |
          cd "$PROJECT_DIR"
          # Only runs if keystore variables are set in the android_keystore group
          if [ -n "$CM_KEYSTORE" ]; then
            echo "📱 Setting up Android keystore..."
            mkdir -p android/app
            echo "$CM_KEYSTORE" | base64 --decode > android/app/$CM_KEYSTORE_FILENAME
            echo "✅ Android keystore configured"
          else
            echo "ℹ️ No keystore configured - building unsigned APK"
          fi

      # 8. Compile Android APK (alternative approach)
      - name: Compile Android APK
        script: |
          cd "$PROJECT_DIR"/android
          # Set environment variables for Android build
          export NODE_ENV=production
          export EXPO_NO_DOTENV=1
          # Make gradlew executable
          chmod +x ./gradlew
          # Try to build APK with fallback strategies
          echo "🔄 Attempting to build APK with standard method..."
          if ./gradlew assembleRelease --no-daemon --stacktrace --info; then
            echo "✅ APK built successfully with standard method"
          else
            echo "❌ Standard method failed, trying with debug build..."
            ./gradlew assembleDebug --no-daemon --stacktrace --info
          fi

    artifacts:
      # Collect APK(s) produced during the build
      - "$PROJECT_DIR/android/app/build/outputs/**/*.apk"

    # Optional: You can configure email notifications in Codemagic UI instead of here 