name: Build Android App Bundle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-bundle:
    name: Build Release AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Cache Gradle wrapper and caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install project dependencies (npm ci)
        run: npm ci --legacy-peer-deps

      - name: Prebuild native Android project via Expo
        run: npx expo prebuild --platform android --non-interactive --no-install --project-root apps/mobile

      - name: Build release AAB with Gradle
        run: |
          cd apps/mobile/android
          ./gradlew bundleRelease --stacktrace --no-daemon

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: apps/mobile/android/app/build/outputs/bundle/release/app-release.aab 